######################################################################
# Automatically generated by qmake (2.00a) ven 9. giu 14:57:21 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h SerialPort.h 
SOURCES += main.cpp mainwindow.cpp SerialPort.cpp
