######################################################################
# Automatically generated by qmake (2.00a) mar 29. ago 11:13:23 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h SerialPort.h
SOURCES += main.cpp mainwindow.cpp SerialPort.cpp
